### ISSUE TITLE
How to use this Markdown Editor outside Contenful? 

### ISSUE THREAD

**Issue by DjGamerDz** [TinkeringAround/Contentful-Markdown-Editor-UI-Extension#1]
## I'm working on an electron app and I'm using the Showdown Module to render Markdown, I need an editor for my project but I can't find one uses Showdown.
I know about SimpleMDE but it doesn't use it, and yours do, so what can I do for that?

**Comment by TinkeringAround** [comment]
Hi there,

its been a long time when working on this project.
Basically, I was loading the old md State from Contentful and initialize the SimpleMD with this old State.
    
```
simplemde = new SimpleMDE({options});

simplemde.value(oldValue.md);
```

 Then I added a change Event to SimpleMD Object to listen for md Changes.

```
simplemde.codemirror.on('change', function() {
      vue.md = simplemde.value();
});
```

Whenever vue md prop changes due to md changes in SimpleMD, i use showdown to render html from md and save it in vue html prop.

```
this.html = converter.makeHtml(this.md);
```
So the process is quite simple, I am positive it will work just fine on electron as well.
